#!/usr/bin/env python3
"""Generate the human-readable current status from the canonical JSON file."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs" / "status" / "platform.json"
TARGET = ROOT / "docs" / "status" / "CURRENT.md"


def minutes(seconds: float) -> str:
    total = round(seconds)
    return f"{total // 60} 分 {total % 60:02d} 秒"


def render(data: dict) -> str:
    production = data["production"]
    hardware = data["hardware"]
    runtime = data["runtime"]
    performance = data["performance"]
    storage = data["storage"]
    network = data["network"]
    runs = "\n".join(
        f"- `{run['task_id']}`：`{run['elapsed_seconds']:.3f} s`"
        for run in performance["validation_runs"]
    )
    return f"""<!-- GENERATED by tools/update_docs.py; DO NOT EDIT -->
# 量化平台当前状态

唯一数据源：[`platform.json`](platform.json)。本页是已验证状态快照，不是实时监控结果；执行操作前仍应按 Runbook 重新检查目标资源。

总更新时间：`{data['updated_at']}`

对应代码：`{data['source_commit']}`

## 生产服务

验证时间：`{production['verified_at']}`

| 项目 | 当前值 |
|---|---|
| 主机 | `{production['host_alias']}` / `{production['address']}` / `{production['user']}` |
| 操作系统 | `{production['os']}`，kernel `{production['kernel']}` |
| 项目目录 | `{production['project_root']}` |
| Web | [{production['web_url']}]({production['web_url']})，`{production['web_state']}` |
| API | [{production['api_url']}]({production['api_url']})，`{production['api_state']}` |
| Worker | `{production['worker_state']}` |

## 硬件与运行环境

硬件验证时间：`{hardware['verified_at']}`；运行环境验证时间：`{runtime['verified_at']}`。

- CPU：{hardware['cpu']}，{hardware['logical_cpus']} 逻辑 CPU；内存 {hardware['memory']}。
- GPU：{hardware['gpu_count']}× {hardware['gpu_model']}，每张约 {hardware['gpu_memory_each_mib']} MiB，驱动 `{hardware['driver']}`，架构 `{hardware['compute_capability']}`。
- API 镜像：`{runtime['api_image_id']}`。
- Web 镜像：`{runtime['web_image_id']}`。
- 校准 provider：默认 `{runtime['calibration_provider_default']}`，失败回退 `{runtime['calibration_provider_fallback']}`。
- NVMe scratch：`{runtime['scratch_root']}`。

## 最近性能基线

验证时间：`{performance['verified_at']}`。

- 原始 H200：`{performance['baseline_seconds']:.3f} s`（{minutes(performance['baseline_seconds'])}）。
- 优化后两次 CUDA 平均：`{performance['optimized_average_seconds']:.3f} s`（{minutes(performance['optimized_average_seconds'])}）。
- 相对加速：`{performance['speedup']:.2f}×`。
{runs}
- 完整证据：[{performance['evidence']}]({performance['evidence']})。

## 存储与备份

验证时间：`{storage['verified_at']}`。

- 共享输入：`{storage['shared_inputs']}`。
- 任务输出：`{storage['task_outputs']}`；系统快照{'包含' if storage['output_data_in_system_backup'] else '不包含'}该目录。
- NAS：`{storage['nas_share']}` → `{storage['nas_mount']}`；挂载{'持久' if storage['nas_mount_persistent'] else '非持久'}。
- 最新已验证快照：`{storage['latest_verified_snapshot']}`。
- 快照根目录：`{storage['backup_root']}`。
- 验证证据：[{storage['evidence']}]({storage['evidence']})。

## 本机网络

验证时间：`{network['verified_at']}`。

- H200：`{network['h200_route']}`。
- wrs/NAS：`{network['wrs_nas_route']}`。
- Windows 接口索引：`{network['windows_interface_index']}`；路由{'持久' if network['persistent'] else '非持久'}。
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if CURRENT.md is stale")
    args = parser.parse_args()
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    expected = render(data)
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else None
    if args.check:
        if current != expected:
            print(f"stale generated document: {TARGET.relative_to(ROOT)}")
            return 1
        print("generated status is current")
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(expected, encoding="utf-8", newline="\n")
    print(f"updated {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
